//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTrace.Integration.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayTrace.Integration.API.APIKeys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACHCODE.
        /// </summary>
        public static string ACHCODE {
            get {
                return ResourceManager.GetString("ACHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACHMSG.
        /// </summary>
        public static string ACHMSG {
            get {
                return ResourceManager.GetString("ACHMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDTAX.
        /// </summary>
        public static string ADDTAX {
            get {
                return ResourceManager.GetString("ADDTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDTAXIND.
        /// </summary>
        public static string ADDTAXIND {
            get {
                return ResourceManager.GetString("ADDTAXIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDTAXINDLI.
        /// </summary>
        public static string ADDTAXINDLI {
            get {
                return ResourceManager.GetString("ADDTAXINDLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDTAXLI.
        /// </summary>
        public static string ADDTAXLI {
            get {
                return ResourceManager.GetString("ADDTAXLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDTAXRATE.
        /// </summary>
        public static string ADDTAXRATE {
            get {
                return ResourceManager.GetString("ADDTAXRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDTAXRATELI.
        /// </summary>
        public static string ADDTAXRATELI {
            get {
                return ResourceManager.GetString("ADDTAXRATELI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNT.
        /// </summary>
        public static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMOUNTLI.
        /// </summary>
        public static string AMOUNTLI {
            get {
                return ResourceManager.GetString("AMOUNTLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPCODE.
        /// </summary>
        public static string APPCODE {
            get {
                return ResourceManager.GetString("APPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPMSG.
        /// </summary>
        public static string APPMSG {
            get {
                return ResourceManager.GetString("APPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVAL.
        /// </summary>
        public static string APPROVAL {
            get {
                return ResourceManager.GetString("APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVEURL.
        /// </summary>
        public static string ApprovalUrl {
            get {
                return ResourceManager.GetString("ApprovalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHKEY.
        /// </summary>
        public static string AUTHKEY {
            get {
                return ResourceManager.GetString("AUTHKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVSRESPONSE.
        /// </summary>
        public static string AVSRESPONSE {
            get {
                return ResourceManager.GetString("AVSRESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BADDRESS.
        /// </summary>
        public static string BADDRESS {
            get {
                return ResourceManager.GetString("BADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BADDRESS2.
        /// </summary>
        public static string BADDRESS2 {
            get {
                return ResourceManager.GetString("BADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCEAMOUNT.
        /// </summary>
        public static string BALANCEAMOUNT {
            get {
                return ResourceManager.GetString("BALANCEAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATCHNUM.
        /// </summary>
        public static string BATCHNUM {
            get {
                return ResourceManager.GetString("BATCHNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATCHNUMBER.
        /// </summary>
        public static string BATCHNUMBER {
            get {
                return ResourceManager.GetString("BATCHNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCITY.
        /// </summary>
        public static string BCITY {
            get {
                return ResourceManager.GetString("BCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCOUNTRY.
        /// </summary>
        public static string BCOUNTRY {
            get {
                return ResourceManager.GetString("BCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNAME.
        /// </summary>
        public static string BNAME {
            get {
                return ResourceManager.GetString("BNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSTATE.
        /// </summary>
        public static string BSTATE {
            get {
                return ResourceManager.GetString("BSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZIP.
        /// </summary>
        public static string BZIP {
            get {
                return ResourceManager.GetString("BZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASHADVANCE.
        /// </summary>
        public static string CASHADVANCE {
            get {
                return ResourceManager.GetString("CASHADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCODE.
        /// </summary>
        public static string CCODE {
            get {
                return ResourceManager.GetString("CCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCODELI.
        /// </summary>
        public static string CCODELI {
            get {
                return ResourceManager.GetString("CCODELI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKID.
        /// </summary>
        public static string CHECKID {
            get {
                return ResourceManager.GetString("CHECKID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKIDENTIFIER.
        /// </summary>
        public static string CHECKIDENTIFIER {
            get {
                return ResourceManager.GetString("CHECKIDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKTYPE.
        /// </summary>
        public static string CHECKTYPE {
            get {
                return ResourceManager.GetString("CHECKTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSC.
        /// </summary>
        public static string CSC {
            get {
                return ResourceManager.GetString("CSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSCRESPONSE.
        /// </summary>
        public static string CSCRESPONSE {
            get {
                return ResourceManager.GetString("CSCRESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTID.
        /// </summary>
        public static string CUSTID {
            get {
                return ResourceManager.GetString("CUSTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMDBA.
        /// </summary>
        public static string CUSTOMDBA {
            get {
                return ResourceManager.GetString("CUSTOMDBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMERID.
        /// </summary>
        public static string CUSTOMERID {
            get {
                return ResourceManager.GetString("CUSTOMERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMERRECORD.
        /// </summary>
        public static string CUSTOMERRECORD {
            get {
                return ResourceManager.GetString("CUSTOMERRECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOMERTAXID.
        /// </summary>
        public static string CUSTOMERTAXID {
            get {
                return ResourceManager.GetString("CUSTOMERTAXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTPSWD.
        /// </summary>
        public static string CUSTPSWD {
            get {
                return ResourceManager.GetString("CUSTPSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTRECEIPT.
        /// </summary>
        public static string CUSTRECEIPT {
            get {
                return ResourceManager.GetString("CUSTRECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTREF.
        /// </summary>
        public static string CUSTREF {
            get {
                return ResourceManager.GetString("CUSTREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCIND.
        /// </summary>
        public static string DCIND {
            get {
                return ResourceManager.GetString("DCIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDA.
        /// </summary>
        public static string DDA {
            get {
                return ResourceManager.GetString("DDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLINEURL.
        /// </summary>
        public static string DECLINEURL {
            get {
                return ResourceManager.GetString("DECLINEURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNT.
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNTIND.
        /// </summary>
        public static string DISCOUNTIND {
            get {
                return ResourceManager.GetString("DISCOUNTIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNTLI.
        /// </summary>
        public static string DISCOUNTLI {
            get {
                return ResourceManager.GetString("DISCOUNTLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNTRATE.
        /// </summary>
        public static string DISCOUNTRATE {
            get {
                return ResourceManager.GetString("DISCOUNTRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUTY.
        /// </summary>
        public static string DUTY {
            get {
                return ResourceManager.GetString("DUTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDATE.
        /// </summary>
        public static string EDATE {
            get {
                return ResourceManager.GetString("EDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLEPARTIALAUTH.
        /// </summary>
        public static string ENABLEPARTIALAUTH {
            get {
                return ResourceManager.GetString("ENABLEPARTIALAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPMNTH.
        /// </summary>
        public static string EXPMNTH {
            get {
                return ResourceManager.GetString("EXPMNTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPYR.
        /// </summary>
        public static string EXPYR {
            get {
                return ResourceManager.GetString("EXPYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX.
        /// </summary>
        public static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCEADDRESS.
        /// </summary>
        public static string FORCEADDRESS {
            get {
                return ResourceManager.GetString("FORCEADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCECSC.
        /// </summary>
        public static string FORCECSC {
            get {
                return ResourceManager.GetString("FORCECSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCEEMAIL.
        /// </summary>
        public static string FORCEEMAIL {
            get {
                return ResourceManager.GetString("FORCEEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREIGHT.
        /// </summary>
        public static string FREIGHT {
            get {
                return ResourceManager.GetString("FREIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREQUENCY.
        /// </summary>
        public static string FREQUENCY {
            get {
                return ResourceManager.GetString("FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDEXP.
        /// </summary>
        public static string IDEXP {
            get {
                return ResourceManager.GetString("IDEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVOICE.
        /// </summary>
        public static string INVOICE {
            get {
                return ResourceManager.GetString("INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST4.
        /// </summary>
        public static string LAST4 {
            get {
                return ResourceManager.GetString("LAST4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEASURE.
        /// </summary>
        public static string MEASURE {
            get {
                return ResourceManager.GetString("MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERCHANTTAXID.
        /// </summary>
        public static string MERCHANTTAXID {
            get {
                return ResourceManager.GetString("MERCHANTTAXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METHOD.
        /// </summary>
        public static string METHOD {
            get {
                return ResourceManager.GetString("METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETAMOUNT.
        /// </summary>
        public static string NETAMOUNT {
            get {
                return ResourceManager.GetString("NETAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETGROSSIND.
        /// </summary>
        public static string NETGROSSIND {
            get {
                return ResourceManager.GetString("NETGROSSIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWCUSTID.
        /// </summary>
        public static string NEWCUSTID {
            get {
                return ResourceManager.GetString("NEWCUSTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWPSWD.
        /// </summary>
        public static string NEWPSWD {
            get {
                return ResourceManager.GetString("NEWPSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWPSWD2.
        /// </summary>
        public static string NEWPSWD2 {
            get {
                return ResourceManager.GetString("NEWPSWD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTAX.
        /// </summary>
        public static string NTAX {
            get {
                return ResourceManager.GetString("NTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDERID.
        /// </summary>
        public static string ORDERID {
            get {
                return ResourceManager.GetString("ORDERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORIGINALID.
        /// </summary>
        public static string ORIGINALID {
            get {
                return ResourceManager.GetString("ORIGINALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGESIZE.
        /// </summary>
        public static string PAGESIZE {
            get {
                return ResourceManager.GetString("PAGESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGESTART.
        /// </summary>
        public static string PAGESTART {
            get {
                return ResourceManager.GetString("PAGESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIALAMOUNT.
        /// </summary>
        public static string PARTIALAMOUNT {
            get {
                return ResourceManager.GetString("PARTIALAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTOID.
        /// </summary>
        public static string PHOTOID {
            get {
                return ResourceManager.GetString("PHOTOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTURL.
        /// </summary>
        public static string POSTURL {
            get {
                return ResourceManager.GetString("POSTURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTID.
        /// </summary>
        public static string PRODUCTID {
            get {
                return ResourceManager.GetString("PRODUCTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSWD.
        /// </summary>
        public static string PSWD {
            get {
                return ResourceManager.GetString("PSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTITY.
        /// </summary>
        public static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECURID.
        /// </summary>
        public static string RECURID {
            get {
                return ResourceManager.GetString("RECURID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECURTYPE.
        /// </summary>
        public static string RECURTYPE {
            get {
                return ResourceManager.GetString("RECURTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUNDAMOUNT.
        /// </summary>
        public static string REFUNDAMOUNT {
            get {
                return ResourceManager.GetString("REFUNDAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUNDCOUNT.
        /// </summary>
        public static string REFUNDCOUNT {
            get {
                return ResourceManager.GetString("REFUNDCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESPONSE.
        /// </summary>
        public static string RESPONSE {
            get {
                return ResourceManager.GetString("RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURNBIN.
        /// </summary>
        public static string RETURNBIN {
            get {
                return ResourceManager.GetString("RETURNBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURNCLR.
        /// </summary>
        public static string RETURNCLR {
            get {
                return ResourceManager.GetString("RETURNCLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURNID.
        /// </summary>
        public static string RETURNID {
            get {
                return ResourceManager.GetString("RETURNID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SADDRESS.
        /// </summary>
        public static string SADDRESS {
            get {
                return ResourceManager.GetString("SADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SADDRESS2.
        /// </summary>
        public static string SADDRESS2 {
            get {
                return ResourceManager.GetString("SADDRESS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALESAMOUNT.
        /// </summary>
        public static string SALESAMOUNT {
            get {
                return ResourceManager.GetString("SALESAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALESCOUNT.
        /// </summary>
        public static string SALESCOUNT {
            get {
                return ResourceManager.GetString("SALESCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCITY.
        /// </summary>
        public static string SCITY {
            get {
                return ResourceManager.GetString("SCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCOUNTRY.
        /// </summary>
        public static string SCOUNTRY {
            get {
                return ResourceManager.GetString("SCOUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCOUNTY.
        /// </summary>
        public static string SCOUNTY {
            get {
                return ResourceManager.GetString("SCOUNTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDATE.
        /// </summary>
        public static string SDATE {
            get {
                return ResourceManager.GetString("SDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCHTEXT.
        /// </summary>
        public static string SEARCHTEXT {
            get {
                return ResourceManager.GetString("SEARCHTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTLED.
        /// </summary>
        public static string SETTLED {
            get {
                return ResourceManager.GetString("SETTLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIPPERS.
        /// </summary>
        public static string SHIPPERS {
            get {
                return ResourceManager.GetString("SHIPPERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIPPINGCOMPANY.
        /// </summary>
        public static string SHIPPINGCOMPANY {
            get {
                return ResourceManager.GetString("SHIPPINGCOMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIPPINGMETHOD.
        /// </summary>
        public static string SHIPPINGMETHOD {
            get {
                return ResourceManager.GetString("SHIPPINGMETHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIPPINGRATE.
        /// </summary>
        public static string SHIPPINGRATE {
            get {
                return ResourceManager.GetString("SHIPPINGRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIPPINGRECORD.
        /// </summary>
        public static string SHIPPINGRECORD {
            get {
                return ResourceManager.GetString("SHIPPINGRECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNAME.
        /// </summary>
        public static string SNAME {
            get {
                return ResourceManager.GetString("SNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCESTATE.
        /// </summary>
        public static string SOURCESTATE {
            get {
                return ResourceManager.GetString("SOURCESTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCEZIP.
        /// </summary>
        public static string SOURCEZIP {
            get {
                return ResourceManager.GetString("SOURCEZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSTATE.
        /// </summary>
        public static string SSTATE {
            get {
                return ResourceManager.GetString("SSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRFWDDATE.
        /// </summary>
        public static string STRFWDDATE {
            get {
                return ResourceManager.GetString("STRFWDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIPE.
        /// </summary>
        public static string SWIPE {
            get {
                return ResourceManager.GetString("SWIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZIP.
        /// </summary>
        public static string SZIP {
            get {
                return ResourceManager.GetString("SZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX.
        /// </summary>
        public static string TAX {
            get {
                return ResourceManager.GetString("TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS.
        /// </summary>
        public static string TERMS {
            get {
                return ResourceManager.GetString("TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTALCOUNT.
        /// </summary>
        public static string TOTALCOUNT {
            get {
                return ResourceManager.GetString("TOTALCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTIONID.
        /// </summary>
        public static string TRANSACTIONID {
            get {
                return ResourceManager.GetString("TRANSACTIONID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSACTIONRECORD.
        /// </summary>
        public static string TRANSACTIONRECORD {
            get {
                return ResourceManager.GetString("TRANSACTIONRECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANXCOUNT.
        /// </summary>
        public static string TRANXCOUNT {
            get {
                return ResourceManager.GetString("TRANXCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANXID.
        /// </summary>
        public static string TRANXID {
            get {
                return ResourceManager.GetString("TRANXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANXTYPE.
        /// </summary>
        public static string TRANXTYPE {
            get {
                return ResourceManager.GetString("TRANXTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UN.
        /// </summary>
        public static string UN {
            get {
                return ResourceManager.GetString("UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNITCOST.
        /// </summary>
        public static string UNITCOST {
            get {
                return ResourceManager.GetString("UNITCOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISAREFUNDAMOUNT.
        /// </summary>
        public static string VISAREFUNDAMOUNT {
            get {
                return ResourceManager.GetString("VISAREFUNDAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISAREFUNDCOUNT.
        /// </summary>
        public static string VISAREFUNDCOUNT {
            get {
                return ResourceManager.GetString("VISAREFUNDCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISASALESAMOUNT.
        /// </summary>
        public static string VISASALESAMOUNT {
            get {
                return ResourceManager.GetString("VISASALESAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISASALESCOUNT.
        /// </summary>
        public static string VISASALESCOUNT {
            get {
                return ResourceManager.GetString("VISASALESCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEIGHT.
        /// </summary>
        public static string WEIGHT {
            get {
                return ResourceManager.GetString("WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN.
        /// </summary>
        public static string WHEN {
            get {
                return ResourceManager.GetString("WHEN", resourceCulture);
            }
        }
    }
}
