//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTrace.Integration.SecureCheckout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecureCheckoutMappings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecureCheckoutMappings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayTrace.Integration.SecureCheckout.SecureCheckoutMappings", typeof(SecureCheckoutMappings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVEURL.
        /// </summary>
        internal static string ApprovalURL {
            get {
                return ResourceManager.GetString("ApprovalURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCEADDRESS.
        /// </summary>
        internal static string ForceAddress {
            get {
                return ResourceManager.GetString("ForceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCECSC.
        /// </summary>
        internal static string ForceCSC {
            get {
                return ResourceManager.GetString("ForceCSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCEEMAIL.
        /// </summary>
        internal static string ForceEmail {
            get {
                return ResourceManager.GetString("ForceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDERID.
        /// </summary>
        internal static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURNURL.
        /// </summary>
        internal static string ReturnURL {
            get {
                return ResourceManager.GetString("ReturnURL", resourceCulture);
            }
        }
    }
}
