'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace SecureCheckout


	Partial Public Class _Default

		''' <summary>
		''' btnStartOrder control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnStartOrder As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' pnl_response control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pnl_response As Global.System.Web.UI.WebControls.Panel

		''' <summary>
		''' lblResponce control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblResponce As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' lblOrderID control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblOrderID As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' lblAUTHKEY control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblAUTHKEY As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' lnkSendToBilling control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lnkSendToBilling As Global.System.Web.UI.WebControls.HyperLink
	End Class
End Namespace
