'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute()>

' Original file name:
' Generation date: 4/30/2012 1:56:29 PM
Namespace SilentPostResponse

	''' <summary>
	''' There are no comments for PostModelEntities in the schema.
	''' </summary>
	Partial Public Class PostModelEntities
		Inherits System.Data.Objects.ObjectContext

		''' <summary>
		''' Initializes a new PostModelEntities object using the connection string found in the 'PostModelEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=PostModelEntities", "PostModelEntities")
			Me.OnContextCreated()
		End Sub
		''' <summary>
		''' Initialize a new PostModelEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "PostModelEntities")
			Me.OnContextCreated()
		End Sub
		''' <summary>
		''' Initialize a new PostModelEntities object.
		''' </summary>
		Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
			MyBase.New(connection, "PostModelEntities")
			Me.OnContextCreated()
		End Sub
		Partial Private Sub OnContextCreated()
		End Sub
		''' <summary>
		''' There are no comments for Posts in the schema.
		''' </summary>
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public ReadOnly Property Posts() As Global.System.Data.Objects.ObjectQuery(Of Post)
			Get
				If (Me._Posts Is Nothing) Then
					Me._Posts = MyBase.CreateQuery(Of Post)("[Posts]")
				End If
				Return Me._Posts
			End Get
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Private _Posts As Global.System.Data.Objects.ObjectQuery(Of Post)
		''' <summary>
		''' There are no comments for Posts in the schema.
		''' </summary>
'INSTANT VB NOTE: The parameter post was renamed since it may cause conflicts with calls to static members of the user-defined type with this name:
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Sub AddToPosts(ByVal post_Renamed As Post)
			MyBase.AddObject("Posts", post_Renamed)
		End Sub
	End Class
	''' <summary>
	''' There are no comments for PostModelModel.Post in the schema.
	''' </summary>
	''' <KeyProperties>
	''' id
	''' </KeyProperties>
	<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="PostModelModel", Name:="Post"), Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=True), Global.System.Serializable()> _
	Partial Public Class Post
		Inherits System.Data.Objects.DataClasses.EntityObject

		''' <summary>
		''' Create a new Post object.
		''' </summary>
		''' <param name="id">Initial value of id.</param>
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Shared Function CreatePost(ByVal id As Integer) As Post
'INSTANT VB NOTE: The variable post was renamed since it may cause conflicts with calls to static members of the user-defined type with this name:
			Dim post_Renamed As New Post()
			post_Renamed.id = id
			Return post_Renamed
		End Function
		''' <summary>
		''' There are no comments for property id in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), Global.System.Runtime.Serialization.DataMemberAttribute(), Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Property id() As Integer
			Get
				Return Me._id
			End Get
			Set(ByVal value As Integer)
				Me.OnidChanging(value)
				Me.ReportPropertyChanging("id")
				Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("id")
				Me.OnidChanged()
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Private _id As Integer
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnidChanging(ByVal value As Integer)
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnidChanged()
		End Sub
		''' <summary>
		''' There are no comments for property OrderID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute(), Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Property OrderID() As String
			Get
				Return Me._OrderID
			End Get
			Set(ByVal value As String)
				Me.OnOrderIDChanging(value)
				Me.ReportPropertyChanging("OrderID")
				Me._OrderID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("OrderID")
				Me.OnOrderIDChanged()
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Private _OrderID As String
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnOrderIDChanging(ByVal value As String)
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnOrderIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for property TransactionID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute(), Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Property TransactionID() As String
			Get
				Return Me._TransactionID
			End Get
			Set(ByVal value As String)
				Me.OnTransactionIDChanging(value)
				Me.ReportPropertyChanging("TransactionID")
				Me._TransactionID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("TransactionID")
				Me.OnTransactionIDChanged()
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Private _TransactionID As String
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnTransactionIDChanging(ByVal value As String)
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnTransactionIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for property Message in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute(), Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Property Message() As String
			Get
				Return Me._Message
			End Get
			Set(ByVal value As String)
				Me.OnMessageChanging(value)
				Me.ReportPropertyChanging("Message")
				Me._Message = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Message")
				Me.OnMessageChanged()
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Private _Message As String
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnMessageChanging(ByVal value As String)
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnMessageChanged()
		End Sub
		''' <summary>
		''' There are no comments for property AppCode in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute(), Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Property AppCode() As String
			Get
				Return Me._AppCode
			End Get
			Set(ByVal value As String)
				Me.OnAppCodeChanging(value)
				Me.ReportPropertyChanging("AppCode")
				Me._AppCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("AppCode")
				Me.OnAppCodeChanged()
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Private _AppCode As String
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnAppCodeChanging(ByVal value As String)
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnAppCodeChanged()
		End Sub
		''' <summary>
		''' There are no comments for property Date in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute(), Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Public Property [Date]() As Global.System.DateTime?
			Get
				Return Me._Date
			End Get
			Set(ByVal value? As Date)
				Me.OnDateChanging(value)
				Me.ReportPropertyChanging("Date")
				Me._Date = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("Date")
				Me.OnDateChanged()
			End Set
		End Property
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Private _Date? As Global.System.DateTime
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnDateChanging(ByVal value? As Global.System.DateTime)
		End Sub
		<Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")> _
		Partial Private Sub OnDateChanged()
		End Sub
	End Class
End Namespace
